version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://db_login@postgres/app_db
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --reload --debugger
    restart: on-failure:10
    volumes:
    - ./app:/code/app
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_login
      - POSTGRES_DB=app_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
