version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://db_login@postgres/app_db
    ports:
      - "80:80"
    command: gunicorn --bind 0.0.0.0:80 'app:create_app()'
    restart: on-failure:10
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_login
      - POSTGRES_DB=app_db
      - POSTGRES_HOST_AUTH_METHOD=trust
